---
title: "MEDA Output:"
author: "MEDA"
output:
  html_document:
    fig_caption: yes
    fig_height: 8
    fig_width: 8
    echo: FALSE
    highlight: pygments
    number_sections: yes
    theme: cerulean
    toc: yes
---


```{r setup, echo = FALSE}
opts_chunk$set(cache=FALSE, echo=FALSE, fig.height = 8, fig.width= 8,
               warning=FALSE, message=FALSE, fig.show='hold',
               comment="#", fig.keep='low')
```

# Structure
## Column types
```{r cc-str1, results = 'hold'}
print(colStr)
```
## Missing values, NAs, and Negatives
```{r cc-str2, results = 'hold'}
print(paste("Are all rows complete?:", complete))
print(paste("Are there any NAs?:", nas))
print(paste("Are any values negative?:", negs))
```
```{r cc-str3, results = 'hold'}
if(p <= 12) { print("Structure"); str(dat) }
```

# Heatmap of scaled data
```{r cc-heatmap}
if(use.plotly){
  p.try(p.heat, dat, TRUE)
} else {
  tryCatch(ggplotly(p.try(p.heat, dat, FALSE)))
}
```

# Violin Plot
```{r cc-violin}
if(use.plotly){
  tryCatch(ggplotly(p.try(p.violin, dat)))
} else {
  p.try(p.violin, dat)
}
```

# Correlation Plot
```{r cc-corr}
tryCatch(do.call(corrplot, p.cor(dat)))
```

# Outlier Plots
```{r cc-outlier}
if(use.plotly){
  ggplotly(p.try(p.outlier, dat))
} else {
  p.try(p.outlier, dat)
}
```

# Cumulative Variance 
```{r cc-cumsum}
if(use.plotly){
  tryCatch(ggplotly(p.try(p.cumvar, dat)))
} else {
  p.try(p.cumvar, dat)
}
```

# Pairs Plots 
```{r cc-pairs, fig.height = 8, fig.width = 8}
p.try(p.pairs, dat)
```

# BIC Plots 
```{r cc-bic}
p.try(p.bic, dat)
```

# Mclust classifications
```{r cc-mclust}
p.try(p.mclust, dat)
```





